"use strict";
const assert = require("node:assert/strict"); const fs = require("node:fs"); const os = require("node:os"); const path = require("node:path"); const test = require("node:test"); const { importContentObject } = require("../lib/content-object-store.js"); const { persistAniccaDaily, persistAttributionCoverage, persistHonneDaily, persistWeeklyReview } = require("./marketing-product-summary.js");

test("attribution coverage shows D7 cohort date, sample size, experimental status, and source gaps", () => {
  const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), "lm-attribution-summary-")); const day = "2026-10-04"; const objectDir = path.join(dataDir, "objects");
  const source = path.join(dataDir, "source.json"); fs.writeFileSync(source, "{}\n"); const ref = importContentObject(source, { objectDir }).ref;
  const ascDir = path.join(dataDir, "tenants/dais-local/marketing/attribution/asc", day); fs.mkdirSync(ascDir, { recursive: true });
  const metricUnavailable = { status: "unavailable", value: null, reason: "report_pending" };
  const metricsUnavailable = Object.fromEntries(["first_time_downloads", "impressions", "unique_impressions", "product_page_views", "unique_product_page_views", "impression_to_page_view", "page_view_to_install", "impression_to_install", "install_to_paid"].map((name) => [name, metricUnavailable]));
  const ascProducts = [
    { product_id: "anicca-ios", source_status: "measured", metrics: { first_time_downloads: { status: "measured", value: 3 }, unique_impressions: { status: "measured", value: 10 }, impression_to_install: { status: "measured", value: 0.3 }, page_view_to_install: { status: "unavailable", value: null, reason: "denominator_zero" }, install_to_paid: { status: "measured", value: 0, numerator: 0, denominator: 3, sample_size: 3, rate_percent: 0, rate_precision: 0, cohort_date: "2026-09-26", cohort_window_days: 7, experimental: true, observed_at: "2026-10-04T00:00:00.000Z", source_refs: ["asc-r3:04c74879:instance", "asc-web-cohort:6755129214:2026-09-26:d7"] } } },
    { product_id: "honne-ai", source_status: "unavailable", metrics: { first_time_downloads: { status: "unavailable", value: null, reason: "report_pending" }, install_to_paid: { status: "unavailable", value: null, reason: "cohort_denominator_unavailable", experimental: true, source_refs: [] } } },
    ...["dhamma-quotes", "sleep-reset", "studio-cherie", "thankful"].map((product_id) => ({ product_id, source_status: "unavailable", metrics: { ...metricsUnavailable } })),
  ];
  fs.writeFileSync(path.join(ascDir, "acquisition.json"), JSON.stringify({ snapshot_ref: ref, products: ascProducts }));
  const rcDir = path.join(dataDir, "tenants/dais-local/marketing/attribution/revenuecat", day); fs.mkdirSync(rcDir, { recursive: true });
  fs.writeFileSync(path.join(rcDir, "subscriptions.json"), JSON.stringify({ snapshot_ref: ref, products: ["anicca-ios", "honne-ai"].map((product_id) => ({ product_id, source_status: "unavailable", metrics: { trial_starts: { status: "unavailable", value: null, reason: "missing" }, active_subscriptions: { status: "unavailable", value: null, reason: "missing" }, renewals: { status: "unavailable", value: null, reason: "missing" }, cancellations: { status: "unavailable", value: null, reason: "missing" }, proceeds_usd: { status: "unavailable", value: null, reason: "missing" } } })) }));
  const first = persistAttributionCoverage(dataDir, day, "2026-10-04T00:01:00.000Z"); const replay = persistAttributionCoverage(dataDir, day, "2026-10-04T00:02:00.000Z");
  assert.equal(first.created, true); assert.equal(replay.created, false); assert.equal(first.snapshot.source_refs.length, 2);
  assert.match(first.snapshot.message, /Anicca iOS: Install 3/); assert.match(first.snapshot.message, /Impressions 10/); assert.match(first.snapshot.message, /Impression→Install 0.3/); assert.match(first.snapshot.message, /Install→Paid D7 0\/3=0%（コホート 2026-09-26、n=3、実験的）/); assert.match(first.snapshot.message, /Activation 取得不可/); assert.match(first.snapshot.message, /D1 retention 取得不可/); assert.match(first.snapshot.message, /Honne AI: Install 取得不可/); assert.match(first.snapshot.message, /Install→Paid D7 取得不可（cohort_denominator_unavailable）/); assert.match(first.snapshot.message, /campaign attribution: 取得不可/);
  assert.equal(first.snapshot.products[0].metrics.activation.value, null); assert.equal(first.snapshot.products[0].metrics.d7_retention.value, null);
});

test("daily acquisition coverage lists every published app and leaves absent RevenueCat rows unavailable", () => {
  const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), "lm-published-app-summary-")); const day = "2026-10-03"; const objectDir = path.join(dataDir, "objects");
  const source = path.join(dataDir, "source.json"); fs.writeFileSync(source, "{}\n"); const ref = importContentObject(source, { objectDir }).ref;
  const productIds = ["anicca-ios", "honne-ai", "dhamma-quotes", "sleep-reset", "studio-cherie", "thankful"];
  const unavailable = { status: "unavailable", value: null, reason: "report_pending" };
  const metricNames = ["first_time_downloads", "impressions", "unique_impressions", "product_page_views", "unique_product_page_views", "impression_to_page_view", "page_view_to_install", "impression_to_install", "install_to_paid"];
  const ascDir = path.join(dataDir, "tenants/dais-local/marketing/attribution/asc", day); fs.mkdirSync(ascDir, { recursive: true });
  fs.writeFileSync(path.join(ascDir, "acquisition.json"), JSON.stringify({ snapshot_ref: ref, products: productIds.map((product_id) => ({ product_id, source_status: "unavailable", metrics: Object.fromEntries(metricNames.map((name) => [name, unavailable])) })) }));
  const rcDir = path.join(dataDir, "tenants/dais-local/marketing/attribution/revenuecat", day); fs.mkdirSync(rcDir, { recursive: true });
  fs.writeFileSync(path.join(rcDir, "subscriptions.json"), JSON.stringify({ snapshot_ref: ref, products: ["anicca-ios", "honne-ai"].map((product_id) => ({ product_id, source_status: "unavailable", metrics: { trial_starts: unavailable, active_subscriptions: unavailable, renewals: unavailable, cancellations: unavailable, proceeds_usd: unavailable } })) }));
  const result = persistAttributionCoverage(dataDir, day, "2026-10-03T13:00:00.000Z");
  assert.deepEqual(result.snapshot.products.map(({ product_id }) => product_id), productIds);
  const dhamma = result.snapshot.products.find((product) => product.product_id === "dhamma-quotes");
  assert.equal(dhamma.source_status.revenuecat, "unavailable");
  assert.equal(dhamma.metrics.trials.status, "unavailable");
});

test("Honne daily summary binds EN and JA immutable daily sources and replays", () => {
  const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), "lm-honne-summary-")); const day = "2026-08-22";
  for (const target of [{ owner: "honne_reveal", account: "@honne_reveal", locale: "en", video: "1", views: 208 }, { owner: "honnevideo", account: "@honnevideo", locale: "ja", video: "2", views: 1035 }]) { const directory = path.join(dataDir, "tenants/dais-local/marketing/metrics", target.owner, target.video, "daily"); fs.mkdirSync(directory, { recursive: true }); fs.writeFileSync(path.join(directory, `${day}.json`), JSON.stringify({ kind: "tiktok_daily_metric_digest", window: "daily", observed_at: `2026-08-22T${target.locale === "en" ? "10" : "11"}:00:00.000Z`, account_id: target.account, locale: target.locale, public_url: `https://www.tiktok.com/${target.account}/video/${target.video}`, post: { views: { status: "measured", value: target.views }, likes: { status: "measured", value: 1 }, comments: { status: "measured", value: 0 }, shares: { status: "measured", value: 0 }, saves: { status: "unavailable" }, engagement: { status: "derived", percent: 1 } }, account_metrics: { followers: { status: "measured", value: 5 }, following: { status: "measured", value: 1 }, total_likes: { status: "measured", value: 10 }, videos: { status: "measured", value: 2 } } })); }
  const first = persistHonneDaily(dataDir, day, "2026-08-22T13:00:00.000Z"); const replay = persistHonneDaily(dataDir, day, "2026-08-22T14:00:00.000Z"); assert.equal(first.created, true); assert.equal(replay.created, false); assert.equal(first.snapshot.source_refs.length, 2); assert.match(first.snapshot.message, /@honne_reveal TikTok: Views 208/); assert.match(first.snapshot.message, /@honnevideo TikTok: Views 1035/); assert.match(first.snapshot.message, /Funnel: Install 取得不可、Impressions 取得不可、Impression→Install 取得不可、Install→Paid D7 取得不可、Activation 取得不可/); assert.equal(fs.statSync(first.file).mode & 0o777, 0o600);
});

test("Anicca daily summary binds main sources and keeps JP4 and HE unavailable", () => {
  const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), "lm-anicca-summary-")); const day = "2026-08-22"; const rows = [{ owner: "anicca.jp", account: "@anicca.jp", platform: "tiktok", url: "https://www.tiktok.com/@anicca.jp/video/1" }, { owner: "anicca.ios.jp", account: "@anicca.jp1", platform: "instagram", url: "https://www.instagram.com/reel/ABC123/" }];
  for (const [index, target] of rows.entries()) { const directory = path.join(dataDir, "tenants/dais-local/marketing/metrics", target.owner, String(index + 1), "daily"); fs.mkdirSync(directory, { recursive: true }); fs.writeFileSync(path.join(directory, `${day}.json`), JSON.stringify({ kind: `${target.platform}_daily_metric_digest`, window: "daily", observed_at: `2026-08-22T1${index}:00:00.000Z`, account_id: target.account, locale: "ja", public_url: target.url, post: { views: { status: "measured", value: 100 + index }, likes: { status: "measured", value: 1 }, comments: { status: "measured", value: 0 }, shares: { status: "measured", value: 0 }, saves: { status: "unavailable" }, engagement: { status: "derived", percent: 1 } }, account_metrics: { status: "unavailable" } })); }
  const result = persistAniccaDaily(dataDir, day, "2026-08-22T13:00:00.000Z"); assert.equal(result.created, true); assert.equal(result.snapshot.source_refs.length, 2); assert.match(result.snapshot.message, /@anicca\.jp TikTok: Views 100/); assert.match(result.snapshot.message, /@anicca\.jp1 Instagram: Views 101/); assert.match(result.snapshot.message, /@anicca\.jp4 TikTok: 全social\/account metrics取得不可/); assert.match(result.snapshot.message, /@anicca\.he TikTok: 全social\/account metrics取得不可/); assert.match(result.snapshot.message, /7676500512308481296/);
});

test("weekly review binds both products without cross-product winner transfer", () => {
  const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), "lm-weekly-summary-")); const day = "2026-08-22";
  for (const [product, label] of [["honne-ai", "Honne AI"], ["anicca-ios", "Anicca iOS"]]) { const directory = path.join(dataDir, "tenants/dais-local/marketing/metrics/summaries", product, "daily"); fs.mkdirSync(directory, { recursive: true }); fs.writeFileSync(path.join(directory, `${day}.json`), JSON.stringify({ schema_version: 1, kind: "marketing_product_metric_summary", period: "daily", report_key: day, observed_at: "2026-08-22T13:00:00.000Z", product_id: product, source_refs: [], message: `Life Manager::: ${label} source values` })); }
  const first = persistWeeklyReview(dataDir, day, "2026-08-22T14:00:00.000Z"); const replay = persistWeeklyReview(dataDir, day, "2026-08-22T15:00:00.000Z"); assert.equal(first.created, true); assert.equal(replay.created, false); assert.equal(first.snapshot.period, "weekly"); assert.equal(first.snapshot.report_key, "2026-W34"); assert.equal(first.snapshot.source_refs.length, 2); assert.match(first.snapshot.message, /Honne AI source values/); assert.match(first.snapshot.message, /Anicca iOS source values/); assert.match(first.snapshot.message, /Cross-product winner: 判定しない/); assert.match(first.snapshot.message, /Attribution coverage: 取得不可/); assert.equal(fs.statSync(first.file).mode & 0o777, 0o600);
});
