#!/usr/bin/env bash
# Sourced by every Writer entrypoint. One contract for repository code,
# mutable state, logs and credentials in both local and cloud runtimes.

WRITER_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
_WRITER_ROOT_CALLER="${ARTICLE_ROOT:-${ARTICLE_SKILL_DIR:-$(cd "$WRITER_SCRIPT_DIR/.." && pwd -P)}}"
_WRITER_REPO_CALLER="${LIFE_MANAGER_REPO:-$(cd "$_WRITER_ROOT_CALLER/../.." && pwd -P)}"
_WRITER_STATE_CALLER="${WRITER_STATE_DIR:-${ARTICLE_STATE_DIR:-${LIFE_MANAGER_STATE_ROOT:-$HOME/.local/state/life-manager/writer}}}"
_WRITER_LOG_CALLER="${WRITER_LOG_DIR:-$_WRITER_STATE_CALLER/logs}"
_WRITER_ENV_CALLER="${LIFE_MANAGER_ENV_FILE:-$HOME/.local/state/life-manager/.env}"
_LIFE_MANAGER_SOURCE_REPO_CALLER="${LIFE_MANAGER_SOURCE_REPO:-}"
_ARTICLE_PROVIDER_CALLER="${ARTICLE_PROVIDER:-}"
_ARTICLE_MODEL_ROOT_CALLER="${ARTICLE_MODEL_ROOT:-}"
_ARTICLE_MODEL_STATE_ROOT_CALLER="${ARTICLE_MODEL_STATE_ROOT:-}"
_ARTICLE_MODEL_LOG_CALLER="${ARTICLE_MODEL_LOG:-}"
_ARTICLE_PROVIDER_HEALTH_CALLER="${ARTICLE_PROVIDER_HEALTH:-}"
_ARTICLE_MODEL_RUNNER_CALLER="${ARTICLE_MODEL_RUNNER:-}"
_ARTICLE_CLAUDE_BIN_CALLER="${ARTICLE_CLAUDE_BIN:-}"
_ARTICLE_CODEX_BIN_CALLER="${ARTICLE_CODEX_BIN:-}"
_ARTICLE_CODEX_PROVIDER_ID_CALLER="${ARTICLE_CODEX_PROVIDER_ID:-}"
_ARTICLE_CODEX_PROVIDER_BASE_URL_CALLER="${ARTICLE_CODEX_PROVIDER_BASE_URL:-}"
_ARTICLE_CODEX_PROVIDER_ENV_KEY_CALLER="${ARTICLE_CODEX_PROVIDER_ENV_KEY:-}"
_ARTICLE_CODEX_PROVIDER_API_KEY_SOURCE_CALLER="${ARTICLE_CODEX_PROVIDER_API_KEY_SOURCE:-}"
# Prefer the Life Manager managed venv when the caller did not explicitly
# choose a Python.  It carries the browser-only dependencies (cloakbrowser,
# Playwright, websocket client) required by Note/X staging; explicit launchd
# or user overrides still win.
_WRITER_MANAGED_PYTHON_DEFAULT="$HOME/.local/share/life-manager/venv/bin/python"
if [ -x "$_WRITER_MANAGED_PYTHON_DEFAULT" ]; then
  _WRITER_PYTHON_DEFAULT="$_WRITER_MANAGED_PYTHON_DEFAULT"
else
  _WRITER_PYTHON_DEFAULT="$(command -v python3)"
fi
_WRITER_PYTHON_CALLER="${LIFE_MANAGER_PYTHON:-$_WRITER_PYTHON_DEFAULT}"
_WRITER_BROWSER_PYTHON_CALLER="${WRITER_BROWSER_PYTHON:-$_WRITER_PYTHON_CALLER}"
_WRITER_CLOAK_PYTHON_CALLER="${WRITER_CLOAK_PYTHON:-$_WRITER_BROWSER_PYTHON_CALLER}"
_ZENN_REPOSITORY_URL_CALLER="${ZENN_REPOSITORY_URL:-}"
_ZENN_ACCOUNT_CALLER="${ZENN_ACCOUNT:-}"
_ZENN_GIT_NAME_CALLER="${ZENN_GIT_NAME:-}"
_ZENN_GIT_EMAIL_CALLER="${ZENN_GIT_EMAIL:-}"
_ARTICLE_MEDIA_RAW_BASE_CALLER="${ARTICLE_MEDIA_RAW_BASE:-}"

# shellcheck source=../../../apps/life-manager/scripts/lib/load-env-file.sh
source "$_WRITER_REPO_CALLER/apps/life-manager/scripts/lib/load-env-file.sh"
lm_load_env_file "$_WRITER_ENV_CALLER"

# Dotenv is for credentials and operator defaults, not release ownership or
# provider routing.  Restore the caller's immutable launchd contract and drop
# executable overrides that were not explicitly supplied by that caller.
restore_writer_value() {
  local key="$1" value="$2"
  if [ -n "$value" ]; then
    export "$key=$value"
  fi
}
clear_writer_override() {
  local key="$1" value="$2"
  if [ -n "$value" ]; then
    export "$key=$value"
  else
    unset "$key"
  fi
}
restore_writer_value ARTICLE_PROVIDER "$_ARTICLE_PROVIDER_CALLER"
restore_writer_value ARTICLE_MODEL_ROOT "$_ARTICLE_MODEL_ROOT_CALLER"
restore_writer_value ARTICLE_MODEL_STATE_ROOT "$_ARTICLE_MODEL_STATE_ROOT_CALLER"
restore_writer_value ARTICLE_MODEL_LOG "$_ARTICLE_MODEL_LOG_CALLER"
restore_writer_value ARTICLE_PROVIDER_HEALTH "$_ARTICLE_PROVIDER_HEALTH_CALLER"
clear_writer_override ARTICLE_MODEL_RUNNER "$_ARTICLE_MODEL_RUNNER_CALLER"
clear_writer_override ARTICLE_CLAUDE_BIN "$_ARTICLE_CLAUDE_BIN_CALLER"
clear_writer_override ARTICLE_CODEX_BIN "$_ARTICLE_CODEX_BIN_CALLER"
restore_writer_value ARTICLE_CODEX_PROVIDER_ID "$_ARTICLE_CODEX_PROVIDER_ID_CALLER"
restore_writer_value ARTICLE_CODEX_PROVIDER_BASE_URL "$_ARTICLE_CODEX_PROVIDER_BASE_URL_CALLER"
restore_writer_value ARTICLE_CODEX_PROVIDER_ENV_KEY "$_ARTICLE_CODEX_PROVIDER_ENV_KEY_CALLER"
restore_writer_value ARTICLE_CODEX_PROVIDER_API_KEY_SOURCE "$_ARTICLE_CODEX_PROVIDER_API_KEY_SOURCE_CALLER"

# Dotenv contains credentials, never path ownership. Preserve the caller's
# immutable release and registry-selected writable roots across sourcing.
WRITER_ROOT="$_WRITER_ROOT_CALLER"
LIFE_MANAGER_REPO="$_WRITER_REPO_CALLER"
WRITER_STATE_DIR="$_WRITER_STATE_CALLER"
WRITER_LOG_DIR="$_WRITER_LOG_CALLER"
LIFE_MANAGER_ENV_FILE="$_WRITER_ENV_CALLER"
LIFE_MANAGER_SOURCE_REPO="${_LIFE_MANAGER_SOURCE_REPO_CALLER:-${LIFE_MANAGER_SOURCE_REPO:-}}"
LIFE_MANAGER_PYTHON="$_WRITER_PYTHON_CALLER"
WRITER_BROWSER_PYTHON="$_WRITER_BROWSER_PYTHON_CALLER"
WRITER_CLOAK_PYTHON="$_WRITER_CLOAK_PYTHON_CALLER"
ZENN_REPOSITORY_URL="${_ZENN_REPOSITORY_URL_CALLER:-${ZENN_REPOSITORY_URL:-}}"
ZENN_ACCOUNT="${_ZENN_ACCOUNT_CALLER:-${ZENN_ACCOUNT:-}}"
ZENN_GIT_NAME="${_ZENN_GIT_NAME_CALLER:-${ZENN_GIT_NAME:-}}"
ZENN_GIT_EMAIL="${_ZENN_GIT_EMAIL_CALLER:-${ZENN_GIT_EMAIL:-}}"
ARTICLE_MEDIA_RAW_BASE="${_ARTICLE_MEDIA_RAW_BASE_CALLER:-${ARTICLE_MEDIA_RAW_BASE:-}}"
unset _WRITER_ROOT_CALLER _WRITER_REPO_CALLER _WRITER_STATE_CALLER
unset _WRITER_LOG_CALLER _WRITER_ENV_CALLER _WRITER_PYTHON_CALLER
unset _LIFE_MANAGER_SOURCE_REPO_CALLER
unset _WRITER_BROWSER_PYTHON_CALLER _WRITER_CLOAK_PYTHON_CALLER
unset _ZENN_REPOSITORY_URL_CALLER _ZENN_ACCOUNT_CALLER _ZENN_GIT_NAME_CALLER
unset _ZENN_GIT_EMAIL_CALLER _ARTICLE_MEDIA_RAW_BASE_CALLER
unset _ARTICLE_PROVIDER_CALLER _ARTICLE_MODEL_ROOT_CALLER
unset _ARTICLE_MODEL_STATE_ROOT_CALLER _ARTICLE_MODEL_LOG_CALLER
unset _ARTICLE_PROVIDER_HEALTH_CALLER _ARTICLE_MODEL_RUNNER_CALLER
unset _ARTICLE_CLAUDE_BIN_CALLER _ARTICLE_CODEX_BIN_CALLER
unset _ARTICLE_CODEX_PROVIDER_ID_CALLER _ARTICLE_CODEX_PROVIDER_BASE_URL_CALLER
unset _ARTICLE_CODEX_PROVIDER_ENV_KEY_CALLER _ARTICLE_CODEX_PROVIDER_API_KEY_SOURCE_CALLER

case "$WRITER_STATE_DIR/$WRITER_LOG_DIR" in
  *"/.openclaw/"*|*"/.hermes/"*)
    printf 'writer runtime refuses legacy state/log roots\n' >&2
    return 1
    ;;
esac
ARTICLE_ROOT="$WRITER_ROOT"
ARTICLE_SKILL_DIR="$WRITER_ROOT"
ARTICLE_STATE_DIR="$WRITER_STATE_DIR"
STATE_DIR="$WRITER_STATE_DIR"
NOTE_MCP_DIR="$WRITER_ROOT/vendor/note-mcp"
NOTE_MCP_SRC="$NOTE_MCP_DIR/src"
ZENN_REPO_PATH="$WRITER_STATE_DIR/checkouts/zenn-articles"
NOTE_WORK_ROOT="$WRITER_STATE_DIR/note-work"
ZENN_ARTICLES_REPO="$ZENN_REPO_PATH"
ARTICLE_ZENN_REPO="$ZENN_REPO_PATH"
PYTHONPATH="$NOTE_MCP_SRC${PYTHONPATH:+:$PYTHONPATH}"
export LIFE_MANAGER_REPO LIFE_MANAGER_SOURCE_REPO LIFE_MANAGER_ENV_FILE LIFE_MANAGER_PYTHON WRITER_ROOT WRITER_STATE_DIR WRITER_LOG_DIR
export ARTICLE_ROOT ARTICLE_SKILL_DIR ARTICLE_STATE_DIR STATE_DIR WRITER_BROWSER_PYTHON WRITER_CLOAK_PYTHON
export NOTE_MCP_DIR NOTE_MCP_SRC PYTHONPATH
export NOTE_WORK_ROOT
export ZENN_REPO_PATH ZENN_ARTICLES_REPO ARTICLE_ZENN_REPO ZENN_REPOSITORY_URL ZENN_ACCOUNT
export ZENN_GIT_NAME ZENN_GIT_EMAIL ARTICLE_MEDIA_RAW_BASE

# Model-led live helpers sometimes invoke the interpreter by its conventional
# `python3` name rather than expanding WRITER_BROWSER_PYTHON.  Keep that bare
# command on the same managed venv, so a launchd shell cannot silently fall
# back to Homebrew/system Python and lose cloakbrowser or Pillow.
if [ -x "$WRITER_BROWSER_PYTHON" ]; then
  _WRITER_PYTHON_BIN_DIR="$(cd "$(dirname "$WRITER_BROWSER_PYTHON")" && pwd -P)"
  PATH="$_WRITER_PYTHON_BIN_DIR${PATH:+:$PATH}"
  export PATH
fi
unset _WRITER_PYTHON_BIN_DIR
